### ISSUE TITLE
P1 | Unable to launch EdgeKernel

### ISSUE THREAD

**Issue by bitvijays** [cm16161/Unikernel-Serverless#7]
Dear Chetan,

On trying to launch `EdgeKernel`, I do get a error

```
SPAWNING eval_test_alert.hvt
Traceback (most recent call last):
        16: from EdgeKernel.rb:283:in `<main>'
        15: from EdgeKernel.rb:279:in `main'
        14: from EdgeKernel.rb:201:in `server'
        13: from EdgeKernel.rb:201:in `loop'
        12: from EdgeKernel.rb:208:in `block in server'
        11: from EdgeKernel.rb:208:in `each'
        10: from EdgeKernel.rb:210:in `block (2 levels) in server'
         9: from EdgeKernel.rb:210:in `each'
         8: from EdgeKernel.rb:211:in `block (3 levels) in server'
         7: from /var/lib/gems/2.5.0/gems/redis-queue-0.1.0/lib/redis/queue.rb:33:in `empty?'
         6: from /var/lib/gems/2.5.0/gems/redis-queue-0.1.0/lib/redis/queue.rb:24:in `length'
         5: from /var/lib/gems/2.5.0/gems/redis-4.1.3/lib/redis.rb:1086:in `llen'
         4: from /var/lib/gems/2.5.0/gems/redis-4.1.3/lib/redis.rb:52:in `synchronize'
         3: from /usr/lib/ruby/2.5.0/monitor.rb:226:in `mon_synchronize'
         2: from /var/lib/gems/2.5.0/gems/redis-4.1.3/lib/redis.rb:52:in `block in synchronize'
         1: from /var/lib/gems/2.5.0/gems/redis-4.1.3/lib/redis.rb:1087:in `block in llen'
/var/lib/gems/2.5.0/gems/redis-4.1.3/lib/redis/client.rb:126:in `call': WRONGTYPE Operation against a key holding the wrong kind of value (Redis::CommandError)
```

**Comment by cm16161** [comment]
This is because the data-item in the Redis-Queue is not a list of values. 
Basically, if you have a single "int" then, you cannot query it's length.
When defining a "trigger" which is used in the Configuration Files, it's essential that data is added via "lpush/rpush"

**Comment by cm16161** [comment]
Closing as this is not necessarily an ``EdgeKernel" issue

**Comment by bitvijays** [comment]
Re-opening as of now, will check and close
