### ISSUE TITLE
Error running EdgeKernel.rb server

### ISSUE THREAD

**Issue by bstelea** [cm16161/Unikernel-Serverless#8]
Dear @cm16161,

After following the instructions presented in the Readme file and in the Technical Demonstration of EdgeKernel youtube video, running `sudo ruby EdgeKernel.rb` results with the following error:

```
Traceback (most recent call last):
	12: from EdgeKernel.rb:341:in `<main>'
	11: from EdgeKernel.rb:337:in `main'
	10: from EdgeKernel.rb:198:in `init'
	 9: from EdgeKernel.rb:15:in `check_webdis'
	 8: from /usr/lib/ruby/2.5.0/net/http.rb:485:in `get_response'
	 7: from /usr/lib/ruby/2.5.0/net/http.rb:609:in `start'
	 6: from /usr/lib/ruby/2.5.0/net/http.rb:909:in `start'
	 5: from /usr/lib/ruby/2.5.0/net/http.rb:920:in `do_start'
	 4: from /usr/lib/ruby/2.5.0/net/http.rb:935:in `connect'
	 3: from /usr/lib/ruby/2.5.0/timeout.rb:103:in `timeout'
	 2: from /usr/lib/ruby/2.5.0/timeout.rb:93:in `block in timeout'
	 1: from /usr/lib/ruby/2.5.0/net/http.rb:936:in `block in connect'
/usr/lib/ruby/2.5.0/net/http.rb:939:in `rescue in block in connect': Failed to open TCP connection to 192.168.0.47:7379 (Connection refused - connect(2) for "192.168.0.47" port 7379) (Errno::ECONNREFUSED)
```

, where the IP address has been changed to match the private IP address returned by `ifconfig`.
Running WebDis again, running the `sudo ruby EdgeKernel.rb` command results in the following error:

```
Traceback (most recent call last):
	10082: from EdgeKernel.rb:341:in `<main>'
	10081: from EdgeKernel.rb:338:in `main'
	10080: from EdgeKernel.rb:327:in `server'
	10079: from EdgeKernel.rb:327:in `loop'
	10078: from EdgeKernel.rb:330:in `block in server'
	10077: from EdgeKernel.rb:330:in `each'
	10076: from EdgeKernel.rb:331:in `block (2 levels) in server'
	10075: from EdgeKernel.rb:321:in `monitor_channel'
	 ... 10070 levels...
	    4: from EdgeKernel.rb:235:in `begin_execution'
	    3: from EdgeKernel.rb:235:in `begin_execution'
	    2: from EdgeKernel.rb:235:in `begin_execution'
	    1: from EdgeKernel.rb:235:in `begin_execution'
EdgeKernel.rb:235:in `begin_execution': stack level too deep (SystemStackError)
```

The same errors appeared both when running on Ubuntu Desktop 19.10 and Ubuntu Server 20.04. 
Could you please help me with this issue?

Thank you in advance for your support,

**Comment by cm16161** [comment]
Can you show me lines 11-21 of your ```EdgeKernel.rb``` file please.
It's the ```check_webdis``` function.

**Comment by bstelea** [comment]
Here are lines 11-21 of `EdgeKernel.rb`:

```ruby
def check_webdis
  ip = Socket.ip_address_list.detect(&:ipv4_private?)&.ip_address
  uri = 'http://' + ip.to_s + ':7379/GET/hello'
  uri = URI(uri)
  response = Net::HTTP.get_response(uri)
  if response.code != '200'
    fork { exec('echo error;cd ../webdis; ./webdis') }
    check_webdis
  end
  return
end
```

**Comment by cm16161** [comment]
Found the issue, it had nothing to do with webdis.
There was a recursive function call which resulted in a run-time error.
Fixed in latest commit
